-- MySQL Script generated by MySQL Workbench
-- 02/19/18 18:02:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema briar_server
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `briar_server` ;

-- -----------------------------------------------------
-- Schema briar_server
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `briar_server` DEFAULT CHARACTER SET utf8 ;
USE `briar_server` ;

-- -----------------------------------------------------
-- Table `briar_server`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `briar_server`.`users` ;

CREATE TABLE IF NOT EXISTS `briar_server`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone_generated_id` VARCHAR(64) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `ip` VARCHAR(20) NULL,
  `isActive` TINYINT(1) NOT NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `phone_generated_id_UNIQUE` (`phone_generated_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `briar_server`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `briar_server`.`contacts` ;

CREATE TABLE IF NOT EXISTS `briar_server`.`contacts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_user` INT UNSIGNED NOT NULL,
  `first_user_contact_acceptance` TINYINT(1) NOT NULL,
  `second_user` INT UNSIGNED NOT NULL,
  `second_user_contact_acceptance` TINYINT(1) NOT NULL,
  `isActive` TINYINT(1) NOT NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_contacts_users_idx` (`first_user` ASC),
  INDEX `fk_contacts_users1_idx` (`second_user` ASC),
  CONSTRAINT `fk_contacts_users`
    FOREIGN KEY (`first_user`)
    REFERENCES `briar_server`.`users` (`phone_generated_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contacts_users1`
    FOREIGN KEY (`second_user`)
    REFERENCES `briar_server`.`users` (`phone_generated_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
